// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apodemas/sheepdog/server/mq/MQMessage.proto

package apodemas.sheepdog.server.mq;

public final class MQMessageProtos {
  private MQMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MQMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MQMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MQMessage.MessageType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.MQMessage.MessageType type = 1;</code>
     */
    apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType getType();

    /**
     * <code>string topic = 2;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>string topic = 2;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>.MQMessage.QosType qos = 3;</code>
     */
    int getQosValue();
    /**
     * <code>.MQMessage.QosType qos = 3;</code>
     */
    apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType getQos();

    /**
     * <code>bytes payload = 4;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code MQMessage}
   */
  public  static final class MQMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MQMessage)
      MQMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MQMessage.newBuilder() to construct.
    private MQMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MQMessage() {
      type_ = 0;
      topic_ = "";
      qos_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MQMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              qos_ = rawValue;
              break;
            }
            case 34: {

              payload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apodemas.sheepdog.server.mq.MQMessageProtos.internal_static_MQMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apodemas.sheepdog.server.mq.MQMessageProtos.internal_static_MQMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.class, apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code MQMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FAILURE = 0;</code>
       */
      FAILURE(0),
      /**
       * <code>PUBLISH = 1;</code>
       */
      PUBLISH(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FAILURE = 0;</code>
       */
      public static final int FAILURE_VALUE = 0;
      /**
       * <code>PUBLISH = 1;</code>
       */
      public static final int PUBLISH_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return FAILURE;
          case 1: return PUBLISH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MQMessage.MessageType)
    }

    /**
     * Protobuf enum {@code MQMessage.QosType}
     */
    public enum QosType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AT_MOST_ONCE = 0;</code>
       */
      AT_MOST_ONCE(0),
      /**
       * <code>AT_LEAST_ONCE = 1;</code>
       */
      AT_LEAST_ONCE(1),
      /**
       * <code>EXACTLY_ONCE = 2;</code>
       */
      EXACTLY_ONCE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>AT_MOST_ONCE = 0;</code>
       */
      public static final int AT_MOST_ONCE_VALUE = 0;
      /**
       * <code>AT_LEAST_ONCE = 1;</code>
       */
      public static final int AT_LEAST_ONCE_VALUE = 1;
      /**
       * <code>EXACTLY_ONCE = 2;</code>
       */
      public static final int EXACTLY_ONCE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static QosType valueOf(int value) {
        return forNumber(value);
      }

      public static QosType forNumber(int value) {
        switch (value) {
          case 0: return AT_MOST_ONCE;
          case 1: return AT_LEAST_ONCE;
          case 2: return EXACTLY_ONCE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<QosType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          QosType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<QosType>() {
              public QosType findValueByNumber(int number) {
                return QosType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final QosType[] VALUES = values();

      public static QosType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private QosType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MQMessage.QosType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.MQMessage.MessageType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.MQMessage.MessageType type = 1;</code>
     */
    public apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType getType() {
      @SuppressWarnings("deprecation")
      apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType result = apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType.valueOf(type_);
      return result == null ? apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType.UNRECOGNIZED : result;
    }

    public static final int TOPIC_FIELD_NUMBER = 2;
    private volatile java.lang.Object topic_;
    /**
     * <code>string topic = 2;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QOS_FIELD_NUMBER = 3;
    private int qos_;
    /**
     * <code>.MQMessage.QosType qos = 3;</code>
     */
    public int getQosValue() {
      return qos_;
    }
    /**
     * <code>.MQMessage.QosType qos = 3;</code>
     */
    public apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType getQos() {
      @SuppressWarnings("deprecation")
      apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType result = apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType.valueOf(qos_);
      return result == null ? apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType.UNRECOGNIZED : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 4;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType.FAILURE.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getTopicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topic_);
      }
      if (qos_ != apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType.AT_MOST_ONCE.getNumber()) {
        output.writeEnum(3, qos_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(4, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType.FAILURE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getTopicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topic_);
      }
      if (qos_ != apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType.AT_MOST_ONCE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, qos_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage)) {
        return super.equals(obj);
      }
      apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage other = (apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage) obj;

      if (type_ != other.type_) return false;
      if (!getTopic()
          .equals(other.getTopic())) return false;
      if (qos_ != other.qos_) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (37 * hash) + QOS_FIELD_NUMBER;
      hash = (53 * hash) + qos_;
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MQMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MQMessage)
        apodemas.sheepdog.server.mq.MQMessageProtos.MQMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return apodemas.sheepdog.server.mq.MQMessageProtos.internal_static_MQMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return apodemas.sheepdog.server.mq.MQMessageProtos.internal_static_MQMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.class, apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.Builder.class);
      }

      // Construct using apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        topic_ = "";

        qos_ = 0;

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return apodemas.sheepdog.server.mq.MQMessageProtos.internal_static_MQMessage_descriptor;
      }

      @java.lang.Override
      public apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage getDefaultInstanceForType() {
        return apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.getDefaultInstance();
      }

      @java.lang.Override
      public apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage build() {
        apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage buildPartial() {
        apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage result = new apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage(this);
        result.type_ = type_;
        result.topic_ = topic_;
        result.qos_ = qos_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage) {
          return mergeFrom((apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage other) {
        if (other == apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        if (other.qos_ != 0) {
          setQosValue(other.getQosValue());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.MQMessage.MessageType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.MQMessage.MessageType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MQMessage.MessageType type = 1;</code>
       */
      public apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType getType() {
        @SuppressWarnings("deprecation")
        apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType result = apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType.valueOf(type_);
        return result == null ? apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MQMessage.MessageType type = 1;</code>
       */
      public Builder setType(apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MQMessage.MessageType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>string topic = 2;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 2;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 2;</code>
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 2;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic_ = value;
        onChanged();
        return this;
      }

      private int qos_ = 0;
      /**
       * <code>.MQMessage.QosType qos = 3;</code>
       */
      public int getQosValue() {
        return qos_;
      }
      /**
       * <code>.MQMessage.QosType qos = 3;</code>
       */
      public Builder setQosValue(int value) {
        qos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MQMessage.QosType qos = 3;</code>
       */
      public apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType getQos() {
        @SuppressWarnings("deprecation")
        apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType result = apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType.valueOf(qos_);
        return result == null ? apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MQMessage.QosType qos = 3;</code>
       */
      public Builder setQos(apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage.QosType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        qos_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MQMessage.QosType qos = 3;</code>
       */
      public Builder clearQos() {
        
        qos_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 4;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 4;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 4;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MQMessage)
    }

    // @@protoc_insertion_point(class_scope:MQMessage)
    private static final apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage();
    }

    public static apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MQMessage>
        PARSER = new com.google.protobuf.AbstractParser<MQMessage>() {
      @java.lang.Override
      public MQMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MQMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MQMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MQMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public apodemas.sheepdog.server.mq.MQMessageProtos.MQMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MQMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MQMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+apodemas/sheepdog/server/mq/MQMessage." +
      "proto\"\335\001\n\tMQMessage\022$\n\004type\030\001 \001(\0162\026.MQMe" +
      "ssage.MessageType\022\r\n\005topic\030\002 \001(\t\022\037\n\003qos\030" +
      "\003 \001(\0162\022.MQMessage.QosType\022\017\n\007payload\030\004 \001" +
      "(\014\"\'\n\013MessageType\022\013\n\007FAILURE\020\000\022\013\n\007PUBLIS" +
      "H\020\001\"@\n\007QosType\022\020\n\014AT_MOST_ONCE\020\000\022\021\n\rAT_L" +
      "EAST_ONCE\020\001\022\020\n\014EXACTLY_ONCE\020\002B.\n\033apodema" +
      "s.sheepdog.server.mqB\017MQMessageProtosb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MQMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MQMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MQMessage_descriptor,
        new java.lang.String[] { "Type", "Topic", "Qos", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
